### PR TITLE
feat: replace axios with fetch

### PR DESCRIPTION
**Pull request by irwansyahwii**

### CODE REVIEW

**Comment by raosan** [comment]
Thanks for the PR, i will review it sometimes in this week. In the mean time, can you solve the conflict?

**Comment by irwansyahwii** [comment]
> Thanks for the PR, i will review it sometimes in this week. In the mean time, can you solve the conflict?

@raosan too bad my Mac suddenly stopped working this morning. I have to fix it first before I can solve the conflict. Please be aware that it might need several days :(

**Comment by raosan** [comment]
> > Thanks for the PR, i will review it sometimes in this week. In the mean time, can you solve the conflict?
> 
> @raosan too bad my Mac suddenly stopped working this morning. I have to fix it first before I can solve the conflict. Please be aware that it might need several days :(

Ok, no worries

**Review by sapiderman — APPROVED** [review]
looks good! 👍🏽 👍🏽

**Pull request closed without merging**
